### ISSUE TITLE
请问如何开始

### ISSUE THREAD

**Issue by leizhu1989** [nameczz/markdown-extension#20]
大佬，你好，我已经安装了md2md，并启动了npm start，想请问怎么使用你这个工程呢，是我git下来，该怎么使用呢

**Comment by leizhu1989** [comment]
你好，请问也是需要在你的工程下，npm install 然后npm start吗，我npm install出现如下问题，请问是什么原因呢：
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN deprecated ini@1.3.5: Please update to ini >=1.3.6 to avoid a prototype pollution issue
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated flat@4.1.0: Fixed a prototype pollution security issue in 4.1.0, please upgrade to ^4.1.1 or ^5.0.1.npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-url@0.4.0: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.3: this library is no longer supported
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated vscode-test@1.4.0: This package has been renamed to @vscode/test-electron, please update to the new name
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! code 1
npm ERR! path D:\project\markdown_process\markdown-extension\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: D:\project\Elasticsearch\node-v17.9.1-win-x64\node.exe D:\project\markdown_process\markdown-extension\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'D:\\project\\Elasticsearch\\node-v17.9.1-win-x64\\node.exe',
npm ERR! gyp verb cli   'D:\\project\\markdown_process\\markdown-extension\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@17.9.1 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\project\markdown_process\markdown-extension\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\project\markdown_process\markdown-extension\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\project\markdown_process\markdown-extension\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\project\markdown_process\markdown-extension\node_modules\which\which.js:89:16npm ERR! gyp verb `which` failed     at D:\project\markdown_process\markdown-extension\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\project\markdown_process\markdown-extension\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:199:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\project\markdown_process\markdown-extension\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\project\markdown_process\markdown-extension\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\project\markdown_process\markdown-extension\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\project\markdown_process\markdown-extension\node_modules\which\which.js:89:16npm ERR! gyp verb `which` failed     at D:\project\markdown_process\markdown-extension\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\project\markdown_process\markdown-extension\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:199:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python C:\ProgramData\Anaconda3\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\ProgramData\Anaconda3\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                       ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:398:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1090:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! gyp ERR! System Windows_NT 10.0.22621
npm ERR! gyp ERR! command "D:\\project\\Elasticsearch\\node-v17.9.1-win-x64\\node.exe" "D:\\project\\markdown_process\\markdown-extension\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd D:\project\markdown_process\markdown-extension\node_modules\node-sass
npm ERR! gyp ERR! node -v v17.9.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zhulei\AppData\Local\npm-cache\_logs\2023-07-13T02_01_38_288Z-debug-0.log

**Comment by leizhu1989** [comment]
我在vscode上安装了markdownPreview这个扩展，在md2md的demo里面点击右上角那个zilliz出现md2md error的消息，请问要怎么办呢
